### ISSUE TITLE
[bug] Suspending a remote user doesn't work with 0.18.0-rc1

### ISSUE THREAD

**Issue by fl4nn** [superseriousbusiness/gotosocial#3748]
### Describe the bug with a clear and concise description of what the bug is.

Trying to Suspend a user in the instance settings panel doesn't work after upgrading to the RC.

### What's your GoToSocial Version?

0.18.0-rc1

### GoToSocial Arch

amd64

### What happened?

When clicking the Suspend button nothing happens, the Browser Console spits out an error:
```
Uncaught (in promise) TypeError: field.hasChanged is not a function
    getFormMutations https://boosts.squirrel.pictures/assets/dist/settings.js:17358
    getFormMutations https://boosts.squirrel.pictures/assets/dist/settings.js:17344
    submitForm https://boosts.squirrel.pictures/assets/dist/settings.js:19429
    __awaiter https://boosts.squirrel.pictures/assets/dist/settings.js:19358
    __awaiter https://boosts.squirrel.pictures/assets/dist/settings.js:19354
    submitForm https://boosts.squirrel.pictures/assets/dist/settings.js:19393
    Nb https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    Tb https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    Ub https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    nf https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    se https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    hd https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    Rk https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    Jb https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    hd https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    fd https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    ed https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    pf https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    qf https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    sf https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    sf https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    createRoot https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    [457]< https://boosts.squirrel.pictures/assets/dist/settings.js:34872
    o https://boosts.squirrel.pictures/assets/dist/settings.js:1
    r https://boosts.squirrel.pictures/assets/dist/settings.js:1
    <anonymous> https://boosts.squirrel.pictures/assets/dist/settings.js:1
settings.js:17358:40
    __awaiter https://boosts.squirrel.pictures/assets/dist/settings.js:19354
    submitForm https://boosts.squirrel.pictures/assets/dist/settings.js:19393
    Nb https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    Tb https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    Ub https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    nf https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    se https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    hd https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    Rk https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    Jb https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    hd https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    fd https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    ed https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    (Async: EventListener.handleEvent)
    pf https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    qf https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    sf https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    forEach self-hosted:4297
    sf https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    createRoot https://boosts.squirrel.pictures/assets/dist/settings.js:20742
    [457]< https://boosts.squirrel.pictures/assets/dist/settings.js:34872
    o https://boosts.squirrel.pictures/assets/dist/settings.js:1
    r https://boosts.squirrel.pictures/assets/dist/settings.js:1
    <anonymous> https://boosts.squirrel.pictures/assets/dist/settings.js:1
```

### What you expected to happen?

The Suspension is executed.

### How to reproduce it?

* Search for a (remote) user via `/settings/moderation/accounts/search`
* Select the user
* (Fill in a Reason)
* Check the "Really suspend" box
* Click Suspend

**Comment by tsmethurst** [comment]
Ah thanks! My bug 😁
